FROM node:18-alpine

WORKDIR /app

# Instalar dependencias necesarias
RUN apk add --no-cache sqlite wget

# Copiar archivos del proyecto
COPY . .

# Instalar dependencias
RUN npm install

# Construir la aplicación
RUN npm run build

# Hacer el script de inicialización ejecutable
RUN chmod +x ./scripts/init-db.sh

# Exponer el puerto
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["./scripts/init-db.sh"] 